### ISSUE TITLE
Color Renaming on Palette Regeneration

### ISSUE THREAD

**Issue by AshwinK** [ment-mx/Prism#1]
Hi Team,

First of all, this is awesomeness! Quick question:

Is there a way to maintain the custom names I'm giving the colors that are outputted in the artboard? For example, if I rename "Teal" to "Primary 1" on the output artboard and proceed to add another color to the document colors > regenerate output artboard, then "Primary 1" changes back to "Teal" even if I've locked the layer. Perhaps I'm missing something or doing something incorrectly. Thoughts?

Thanks!
- AK

**Comment by lalomts** [comment]
Thank you, @AshwinK!

You're certainly not doing anything wrong. The plugin right now is completely stateless. Every time you click on "Generate Color Palette" the plugin takes the colors in the _Document Colors_ and creates all the color layers from scratch, assigning the name given in the _Dataset file_. 

We thought the possibility of adding an _alias_ to each color, and we like your approach to changing the color name for each color value if needed. We'll definitely add something that can solve the problem as soon as we can, so stay tuned! 

**– Lalo**

**Comment by Adrxx** [comment]
Fixed! ;)
