### ISSUE TITLE
don't work on sketch 39.1

### ISSUE THREAD

**Issue by selcukyilmaz** [ment-mx/Prism#12]
yes.

**Comment by lalomts** [comment]
Hi, @selcukyilmaz. 
Can you share your Sketch log to debug?

**Comment by selcukyilmaz** [comment]
how?

**Comment by HeavenWesker** [comment]
I have the same issue
Prism version: 1.0.1
Sketch version: 39.1 (31720)

## And I got some logs, hope it useful.

9/10/16 1:12:11.286 AM Sketch Toolbox[93163]: Getting latest info for Prism
9/10/16 1:14:51.523 AM Generate Color Palette (Sketch Plugin)[90050]: TypeError: undefined is not an object (evaluating 'cell.height')
line: 1239
sourceURL: $HOME/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Prism/Prism.sketchplugin/Contents/Sketch/Prism.cocoascript
column: 42
9/10/16 1:14:58.179 AM Export All Colors... (Sketch Plugin)[90050]: TypeError: undefined is not an object (evaluating 'this.artboard.children')
line: 1251
sourceURL: $HOME/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Prism/Prism.sketchplugin/Contents/Sketch/Prism.cocoascript
column: 29
9/10/16 10:12:16.291 AM Sketch Toolbox[94410]: Getting latest info for Prism
9/10/16 10:19:40.632 AM Generate Color Palette (Sketch Plugin)[90050]: TypeError: undefined is not an object (evaluating 'cell.height')
line: 1239
sourceURL: $HOME/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Prism/Prism.sketchplugin/Contents/Sketch/Prism.cocoascript
column: 42
9/10/16 10:24:31.276 AM Generate Color Palette (Sketch Plugin)[90050]: TypeError: undefined is not an object (evaluating 'cell.height')
line: 1239
sourceURL: $HOME/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Prism/Prism.sketchplugin/Contents/Sketch/Prism.cocoascript
column: 42

---

thx
