### ISSUE TITLE
Doesn't appear to work with 41 (35326)

### ISSUE THREAD

**Issue by StefanHinck** [ment-mx/Prism#15]

**Comment by lalomts** [comment]
Hi, @StefanHinck. 
This has been noted, we'll add compatibility as soon as we can.

**Comment by fh-d** [comment]
yep it would be appreciable

**Comment by peterschmidler** [comment]
+1

**Comment by rutger1140** [comment]
I'm thinking about reverting back to an older version of Sketch. This super useful plugin is bolted into my workflow. Can't wait.

**Comment by himynameisubik** [comment]
+1 really looking forward to the updated version for this really essential and useful plugin

**Comment by Adrxx** [comment]
FINALLY FIXED! enjoy ;)

**Comment by himynameisubik** [comment]
Hmm, it doesn't seem to work for me unfortunately :(

**Comment by Adrxx** [comment]
Did you removed the last version of Prism first?

**Comment by himynameisubik** [comment]
Yep, deleted it completely from the plugins folder and installed it form the downloaded Prism-master.zip

**Comment by Adrxx** [comment]
I'm gonna need you to help me by providing some Sketch Logs.
can you run this command from your console and then try to generate de color palette?
`tail -f /var/log/system.log|grep Sketch`
Then show me if something appeared on the console.

**Comment by lalomts** [comment]
It's working fine for me.

**Comment by himynameisubik** [comment]
Sure thing. This is what it shows. And I have document colors set.

> Nov 21 10:24:43 imac Generate Color Palette (Sketch Plugin)[2020]: Generating...
Nov 21 10:24:43 imac Generate Color Palette (Sketch Plugin)[2020]: adasd
Nov 21 10:24:43 imac Generate Color Palette (Sketch Plugin)[2020]: New palette...
Nov 21 10:24:44 imac Sketch[2020]: Exception: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]
Nov 21 10:24:44 imac Generate Color Palette (Sketch Plugin)[2020]: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]

**Comment by Adrxx** [comment]
Try removing any previous Prism Palette Artboard in a the file and be sure you have some document colors added and then try again. Also, are you using the included template.sketch file? or did you customize it?

**Comment by Adrxx** [comment]
Oh and, be sure to be using Sketch version 41, it will not work on older versions.

**Comment by himynameisubik** [comment]
I created a new Sketch file without any artboards besides the newly created and I also didn't edit anything in the plugin I just installed it and clicked on the  "Generate Color Palette" menu item. 

Without any colors added to document colors I get the message below:
![bildschirmfoto 2016-11-22 um 09 42 50](https://cloud.githubusercontent.com/assets/322449/20516724/2c643efa-b098-11e6-941e-f097e8285672.png)

As soon as I add a color, nothing happens.

I am using 41.1
![bildschirmfoto 2016-11-22 um 09 43 13](https://cloud.githubusercontent.com/assets/322449/20516726/2f1891dc-b098-11e6-8496-bed96e2045be.png)

**Comment by LaloMrtnz** [comment]
Hey @himynameisubik are you able to use it on 41.1?

**Comment by himynameisubik** [comment]
Just tried it again but it seems that it's still not working for me. Either because I can't figure out how or it still doesn't work. And I am using 41.1y

//

**Comment by simonc** [comment]
Hello. Not working with Sketch 42 either. ❤️

**Comment by lalomts** [comment]
I'm really sorry to hear that, guys. @simonc @himynameisubik 

Can you provide your log files or any more information that can help us find the issue? I just tried it in Sketch 42 and again, had no problems using the plugin.

**Comment by simonc** [comment]
@LaloMrtnz no worries, shit happens :wink:

Here is what pops up in my console
```
default	15:35:12.551826 +0100	Sketch	0x60000186a6c0 opened /var/folders/90/y7lt76pd6jj7sp0kr3mcv5600000gn/C//mds/mdsObject.db: 4636 bytes
default	15:35:12.552699 +0100	Sketch	0x60000186a6c0 closed /var/folders/90/y7lt76pd6jj7sp0kr3mcv5600000gn/C//mds/mdsObject.db
default	15:35:12.553217 +0100	Sketch	0x600002079ac0 opened /var/folders/90/y7lt76pd6jj7sp0kr3mcv5600000gn/C//mds/mdsDirectory.db: 50744 bytes
default	15:35:12.553290 +0100	Sketch	0x600002079ac0 closed /var/folders/90/y7lt76pd6jj7sp0kr3mcv5600000gn/C//mds/mdsDirectory.db
default	15:35:12.553554 +0100	Sketch	0x600000671580 opened /Users/simonc/Library/Keychains/login.keychain-db: 1247784 bytes
default	15:35:12.554358 +0100	Sketch	0x600000671580 closed /Users/simonc/Library/Keychains/login.keychain-db
default	15:35:12.556176 +0100	Sketch	loading /Users/simonc/Library/Keychains/login.keychain-db
default	15:35:12.558651 +0100	NowPlayingTouchUI	[NowPlayingTouchUI] Reloading available apps due to workspace activating an application: NSConcreteNotification 0x60000004d530 {name = NSWorkspaceDidActivateApplicationNotification; object = <NSWorkspace: 0x60800000e780>; userInfo = {
    NSWorkspaceApplicationKey = "<NSRunningApplication: 0x6000001142e0 (com.bohemiancoding.sketch3 - 10755)>";
}}
default	15:35:12.563471 +0100	Sketch	0x608001a7b5c0 opened /Library/Keychains/System.keychain: 71196 bytes
default	15:35:12.563560 +0100	Sketch	0x608001a7b5c0 closed /Library/Keychains/System.keychain
default	15:35:12.565161 +0100	Sketch	loading /Library/Keychains/System.keychain
default	15:35:15.683803 +0100	Sketch	Generating...
default	15:35:15.684164 +0100	Sketch	adasd
default	15:35:15.723193 +0100	Sketch	New palette...
default	15:35:15.742830 +0100	Sketch	Exception: TypeError: color.hexValue is not a function. (In 'color.hexValue()', 'color.hexValue' is undefined)
default	15:35:15.742954 +0100	Sketch	TypeError: color.hexValue is not a function. (In 'color.hexValue()', 'color.hexValue' is undefined)
line: 1274
sourceURL: /Users/simonc/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Prism.sketchplugin/Contents/Sketch/Prism.cocoascript
column: 51
```

**Comment by Adrxx** [comment]
@simonc You should be using an old version of Prism, as "color.hexValue" is not present in newer versions anymore.

**Comment by simonc** [comment]
@Adrxx I looked in the plugins list it was indicating `1.0.1`. I removed the plugin, downloaded it again and installed it. Still not working.

The error message is the same. Am I supposed to download the _master_ version or something like that?

**Comment by Adrxx** [comment]
To everyone having problems be sure the plugin is on version 1.0.2 :)
