### ISSUE TITLE
Issue with Version 41.1 (35376)

### ISSUE THREAD

**Issue by joshrio** [ment-mx/Prism#16]
Hey Guys,

Seriously the best Sketch Plugin in the world. 

I'm having issues with **Version 41.1 (35376)** and can't seem to get Prism to work. I had a previous version installed, and downloaded the newest version. I installed it, which replaced the previous version. I don't get any error messages but I'm willing to help track down any errors if need be.

**Comment by lalomts** [comment]
Hey, @joshrio, can you help providing more context? Are you using it an existing document or inside a new one?

**Comment by joshrio** [comment]
Hey Lalo,

Sorry for the late reply. I've tried using it on both an existing document and a new document.

**Comment by simonc** [comment]
Hello. I'm running Sketch 41.2 and Prism 1.0.1. When I click on `Generate Color Palette` nothing happens 😞  I'm also available for further information.

We're basing our SCSS color names on our Palette so anything I can do to help I will :wink:

**Comment by simonc** [comment]
I have no idea if it'll be of any help by when running the generation here is what's shown in the macOS Console:

```
default	16:19:16.067130 +0100	Sketch	UNIX error exception: 17
default	16:19:16.067220 +0100	Sketch	0x6000008691c0 opened /private/var/db/mds/system/mdsDirectory.db: 50744 bytes
default	16:19:16.067275 +0100	Sketch	0x6000008691c0 closed /private/var/db/mds/system/mdsDirectory.db
default	16:19:16.067433 +0100	Sketch	UNIX error exception: 17
default	16:19:16.067554 +0100	Sketch	0x600000478dc0 opened /Users/xyz/Library/Keychains/login.keychain-db: 956384 bytes
default	16:19:16.068038 +0100	Sketch	0x600000478dc0 closed /Users/xyz/Library/Keychains/login.keychain-db
default	16:19:16.069859 +0100	Sketch	loading /Users/xyz/Library/Keychains/login.keychain-db
default	16:19:16.073519 +0100	Sketch	0x608000874f80 opened /Library/Keychains/System.keychain: 66864 bytes
default	16:19:16.073590 +0100	Sketch	0x608000874f80 closed /Library/Keychains/System.keychain
default	16:19:16.075000 +0100	Sketch	loading /Library/Keychains/System.keychain
default	16:19:30.145416 +0100	Sketch	UNIX error exception: 17
default	16:19:30.145619 +0100	Sketch	UNIX error exception: 17
default	16:19:30.145740 +0100	Sketch	0x600000471f00 opened /Users/xyz/Library/Keychains/login.keychain-db: 956384 bytes
default	16:19:30.145993 +0100	Sketch	0x600000471f00 closed /Users/xyz/Library/Keychains/login.keychain-db
default	16:19:30.147386 +0100	Sketch	loading /Users/xyz/Library/Keychains/login.keychain-db
default	16:19:30.150338 +0100	Sketch	0x600002e68600 opened /Library/Keychains/System.keychain: 66864 bytes
default	16:19:30.150410 +0100	Sketch	0x600002e68600 closed /Library/Keychains/System.keychain
default	16:19:30.151735 +0100	Sketch	loading /Library/Keychains/System.keychain
```

**Comment by m-rlons** [comment]
The .zip download didn't pull down all of the files that I see here on GitHub. I think that is my main issue. It didn't even pull down the template.sketch file.

**Comment by simonc** [comment]
Just downloaded the .zip from _master_ via the Github download button and the plugin works correctly ☺️

**Comment by simonc** [comment]
Ok, the Download link is not correct in the README, it points to v1.0.1 instead of v1.0.2. I just tried v1.0.2 with Sketch v42 and it works fine! 😄

**Comment by Adrxx** [comment]
😨 !!! That was it! thank you so much @simonc! I'm Closing this an updating the README
