### ISSUE TITLE
Prism is not working

### ISSUE THREAD

**Issue by DopDrop** [ment-mx/Prism#17]
Sketch Version 41.2 (35397)

**Comment by lalomts** [comment]
Hi, @DopDrop, 

I'm using Sketch v. 41.2 and Prism runs without any problem. Can you give more information?

**Comment by DopDrop** [comment]
Hi, @LaloMrtnz 

I tested on two computers
after starting the plug-in vehicle is thinking and as a result does not occur nichegno

**Comment by Adrxx** [comment]
Running Prism in Sketch 42 without any problems. Be sure to have the latest version installed.

**Comment by euheny** [comment]
Sketch 42, Prism - latest. Not working. What information is required?

**Comment by Adrxx** [comment]
Be sure you have version 1.0.2 ;)
