### ISSUE TITLE
Different hex code than in Sketch color panel

### ISSUE THREAD

**Issue by giuseppebergman** [ment-mx/Prism#19]
Hi, and thank you for this nice plugin!

I noticed that hexadecimal values are sometimes different between Sketch color palette, and the palette artwork generated by Prism.
For example: 
- rgb(72, 119, 143) is hex coded as #487**7**8F by Sketch, and coded as #487**6**8F on the palette artwork generated by Prism.
- rgb(184, 214, 230) is hex coded as #B8D7E6 by Sketch, and coded as #B7D6E5 on the palette artwork generated by Prism.

Is it possible to ensure that all codes are the same between Sketch and Prism?

Thanks a lot!

**Comment by lalomts** [comment]
Wow, that one was hard to spot, @giuseppebergman!

**The hex values are actually calculated by Sketch**, so we don't really know whats going on there. 👎 
I think the best way to solve this is to calculate the _hex_ values ourselves based on the _rgba_ values. We'll try to fix it a soon as possible!

**Comment by giuseppebergman** [comment]
Well, I have to align my client's development color palette with my design palette. As we usually share hex values, the bug was spotted pretty quickly…

Anyway, thanks for looking into it even if it's Sketch's mess!

**Comment by lukaspili** [comment]
Any progress on the issue? 
It's bothering our designer :) and the export to Android xml is incorrect because it's using those hex values.

Thanks.

**Comment by lalomts** [comment]
Hello, guys!
The hex color export is now fixed. Please make sure to test the [latest release](https://github.com/ment-mx/Prism/archive/1.0.4.zip) and reach out if you find something else. 😃
