### ISSUE TITLE
Unable to generate sass file

### ISSUE THREAD

**Issue by isratc** [ment-mx/Prism#2]
Hiya,
thankyou for making this plugin! I have created the color palette and it all works fine hoveever, when i try and save the sass file from > generate sass file.  However when i go to folder where its meant to save, its not there? Could you please help me :(

**Comment by lalomts** [comment]
Hi, @isratc! 
I'm trying to recreate the problem but I'm not able to do so. Do you have the problem with a specific document or with all of them? Can you give us more information?

You could help us by sending  what _version of Sketch_ you are running, the _colors_ you were using when encountering the problem and if possible, the _Sketch log_ for us to debug. 

Thanks!

**Comment by isratc** [comment]
Hiya here are the colors. it generates the shareable color palette fine. but doesnt generate sass file. 
It only generate one color only scss file. 
Sass Version 3.7.2 (28276)

heres is the sketch log: 
![screen shot 2016-05-03 at 10 49 04](https://cloud.githubusercontent.com/assets/10596845/14979839/b8eabb5e-111c-11e6-9b94-d87e18ead5db.png)

color palette: 
![screen shot 2016-05-03 at 10 40 49](https://cloud.githubusercontent.com/assets/10596845/14979679/bcba4aca-111b-11e6-97a4-8ff43aba28b2.png)

**Comment by isratc** [comment]
hiya, heres i

**Comment by isratc** [comment]
@LaloMrtnz hiya see above comment thankyou!

**Comment by Adrxx** [comment]
@isratc What's the only color generated in the SCSS file?
