### ISSUE TITLE
[Feature Request] Integrate with Sketchpacks Relay to serve auto-updates

### ISSUE THREAD

**Issue by adamkirkwood** [ment-mx/Prism#20]
More details found @ https://github.com/integration/sketchpacks-relay

Example
![screen shot 2017-03-22 at 4 08 57 pm](https://cloud.githubusercontent.com/assets/52746/24224720/fc40de64-0f19-11e7-8473-a2798193fc33.png)

**Comment by lalomts** [comment]
Hey @adamkirkwood that seems like a great feature to add. We'll check it out!
 Thanks!  💯

**Comment by lalomts** [comment]
It was a nice feature, but with Sketch 45 new plugin update system implemented now, I'm closing the issue.

**Comment by adamkirkwood** [comment]
@LaloMrtnz Understood.

Incase you were curious, you could actually use [Sketchpacks Relay to serve your appcast feed](https://docs.sketchpacks.com/developers/publishing/appcast.html). Our API allows for appcasts to be auto-generated based on your published releases on github. This way, you wouldn't have to maintain your [appcast.xml](https://github.com/ment-mx/Prism/blob/master/Prism.sketchplugin/Contents/Sketch/manifest.json) file.

Also, if you want some simple [download metrics](https://api.sketchpacks.com/v1/plugins/com.utom.measure/rollup), feel free to check out our [badges](https://docs.sketchpacks.com/developers/publishing/badges.html).

Thanks for the feedback!
