### ISSUE TITLE
Prism not working in Sketch 42.

### ISSUE THREAD

**Issue by irpolarbear** [ment-mx/Prism#21]
Just installed the plugin and watched the video for how it's supposed to work. I have my document colors loaded, when I choose "Generate Color Palette", nothing happens. I have uninstalled the plug-in, reinstalled, quit and relaunched Sketch, still nothing. I even went so far as to turn off other plug-ins thinking there could be a conflict. But that didn't work either.

**Comment by irpolarbear** [comment]
Ah ha! Figured it out! The Craft plug-in apparently is in conflict. I didn't turn that one off before because I use it a ton. Decided to disable it and Prism works! So not sure how you can fix that.

**Comment by lalomts** [comment]
Hi, @irpolarbear, 
I also use Craft but have never experienced any problems. Can you tell us what version number of Craft and Prism you're using to figure out what's going on?

**Comment by irpolarbear** [comment]
Hey, @LaloMrtnz - Yeah I am running a beta of Craft (1.4.0), so that is the reason. Only reason I use the beta is because I am testing and using the prototyping functionality. I installed the current production version of Craft (1.7.5) and Prism worked fine. Guess that's the price I pay for being on the bleeding edge.
