### ISSUE TITLE
not working with sketch v43.2

### ISSUE THREAD

**Issue by n8mills** [ment-mx/Prism#23]

**Comment by n8mills** [comment]
not working with sketch v43.2

**Comment by lalomts** [comment]
Hi, @n8mills, 
I just used it on v43.2 and had no problems. Can you make sure you're using the latest version of the plugin? If that doesn't work, please provide the log files so we can find the problem. ;)

**Comment by n8mills** [comment]
In regards to exporting for .xml to file or clipboard?

 

Nathan Mills

 

 

Technical Analysis

Healthcare Human Factors

 

University Health Network

190 Elizabeth St, RF Elliott, 4th Floor

Toronto, Ontario, M5G 2C4, Canada

www.humanfactors.ca

**Comment by n8mills** [comment]
It works now – I had the artboard selected, you have to have the colour “bricks” selected for it to work

 

Thanks!

 

One thing that would be great for a fix it transparent colours. We are using the white and black transparencys as per material design balck .87 .50 etc so theres 4 of them and 4 whites it would be great it it would name these differently as the devs have to change this on their end > black_75 or something along these lines!

 

it would save me a bit of time

 

cheers!

 

Nathan Mills

 

 

Technical Analysis

Healthcare Human Factors

 

University Health Network

190 Elizabeth St, RF Elliott, 4th Floor

Toronto, Ontario, M5G 2C4, Canada

www.humanfactors.ca

**Comment by lalomts** [comment]
Glad it worked. 

About your proposal, you can actually change the name of your colors to whatever you want, you can check the readme file to learn how.  ;)
