### ISSUE TITLE
Exported Sass variable names includes apostrophes

### ISSUE THREAD

**Issue by fiinix** [ment-mx/Prism#24]
When exporting color as Sass variables, the color name, e.g. Payne's grey has its apostrophe included in the Sass variable name which breaks in Sass.
E.g.
`$payne's-grey: #414141;`

Instead of the expected:
`$paynes-grey: #414141;`

I would except the Sass variable names to have special (Sass breaking) characters stripped out. Whilst it's certainly easy to manually edit the names to fix it, some people might find it confusing when the Sass output doesn't conform to Sass standards.

Thank you for a great and time-saving plugin!

**Comment by lalomts** [comment]
Good catch, @fiinix!
I just fixed it, please make shure you clone the latest commit and try it out! 
Thank you! 👍
