### ISSUE TITLE
Add support to export as osx .clr file

### ISSUE THREAD

**Issue by lukaspili** [ment-mx/Prism#26]
Would be great. Thanks!

It would allow to integrate nicely with https://github.com/mac-cain13/R.swift

**Comment by lalomts** [comment]
I'm not familiar with the osx .clr format. Can you explain it's use and how the code should look like please?

**Comment by griffin-stewie** [comment]
@LaloMrtnz Maybe I can help you to code about this issue.

**Comment by griffin-stewie** [comment]
@lukaspili 
clr support was merged #31 :tada:

**Comment by lalomts** [comment]
You're awesome, @griffin-stewie! Thanks a lot for your support!  🤟
