### ISSUE TITLE
Broken in Sketch 44.1

### ISSUE THREAD

**Issue by giuseppebergman** [ment-mx/Prism#27]
Hi, 
It seems the plugin is broken  in Sketch v44.1. Nothing happens after choosing "Generate color palette" from the menu…
I was looking forward to the "fixed hex values" update :( 
Any idea?
Thank you,

**Comment by mmussehl** [comment]
Same case for me and my colleagues.😐

**Comment by lalomts** [comment]
I've found the error. Weird since I checked it before I pushed the commit. However, a new release is up. 

Also, the Sketch 45 version is out. Hopefully the update will be available automatically through Sketch. I would appreciate if you could test it and tell me how it works.

**Comment by mmussehl** [comment]
Great! It's working again. Thanks for fixing this so fast. The update was available in the manage plugins section in sketch.

Greetings from Berlin!

**Comment by giuseppebergman** [comment]
Works for me as well, many thanks for the fix. I'm still in 44.1, so I couldn't test the 45 update system.

Cheers!

**Comment by lalomts** [comment]
Glad it worked! Thanks for the feedback, guys! 😄
