### ISSUE TITLE
Sketch Version 3.7.2

### ISSUE THREAD

**Issue by iGyver** [ment-mx/Prism#3]
Hi, Do you have an issue with that plugin and the current Sketch Version 3.7.2?

[Here you see what happens](https://youtu.be/JIqeDBVo50E)

**Comment by lalomts** [comment]
Hey, @iGyver! 

I can't replicate the issue, but I think I know were it points to. Are you sure you actually have added colors to your **_Document Colors Palette_** ? If not, I'm sure is the problem, the _ShareableColorPalette_ is created based on the colors you added there. 

Please, let us know if that helped!

**Comment by lalomts** [comment]
Hi @iGyver, is the bug persistent or were you able to solve it?

**Comment by NicosKaralis** [comment]
Hi, how do I add colors to the **Document Colors Palette**? I'm using Sketch 3.7.2 and I can't find it anywhere

**Comment by iGyver** [comment]
Hi,

I still have that issue. I created color palette but I can not see anything when I use it. I guess your instructions has some preconditions missed. Please explain more in detail what is to make.

Bye

**Comment by MYFW93** [comment]
Hi.

Not works on Sketch 3.8.2 :(

Thanks for your work man!

**Comment by lalomts** [comment]
Hey, guys! We've updated the plugin, just tested it on 8,3,8 and works perfectly. 

Could you check it out? Your feedback will be appreciated!
