### ISSUE TITLE
Sketch Version 3.8.3 (29802)

### ISSUE THREAD

**Issue by MAJ3STIC** [ment-mx/Prism#4]
Is there an update for Sketch Version 3.8.3 (29802)? The plugin stopped working before this patch even on a un-install/re-install.

**Comment by Adrxx** [comment]
We're working on a new release (3.0) that will work on Sketch >= 3.8.
Tons of new features are coming  ;)

**Comment by MAJ3STIC** [comment]
Do you have an estimated timeframe for the new release? Just wondering if I should utilize another plugin in the meantime.

**Comment by lalomts** [comment]
We'll release an update **next week**. It will only fix the bug that prevents the plugin to ron on the most recent versions of Sketch, so that you guys can continue using the plugin while the new version is released.

**Comment by lalomts** [comment]
Hi! We've just updated the plugin and it should work fine. We tested it on Sketch 8.3.8 and works as expected. 

Could you try it, please? Your feedback will be very much appreciated.

**Comment by MAJ3STIC** [comment]
@LaloMrtnz @Adrxx Thanks so much this fix works perfectly now! Great and amazing work!
