### ISSUE TITLE
Sketch 53 support

### ISSUE THREAD

**Issue by abbrechen** [ment-mx/Prism#42]
When I try to use any feature of Prism in Sketch 53 nothing happens.

**Comment by n8rzz** [comment]
I have that same problem.  I can click to view template, that works, but other than that none of the other options work for me either

**Comment by MAJ3STIC** [comment]
Is this plugin still being supported? I'm also waiting for a patch to the plugin.

**Comment by n8rzz** [comment]
Seems the api may have changed, or at least `document.documentData().assets().colors()` has changed.  See:

- https://github.com/brainly/html-sketchapp/issues/154 
- https://sketchplugins.com/d/792-get-document-colors

**Comment by frankharrison** [comment]
+1 – would be great to have this working again!

**Comment by Adrxx** [comment]
Will check this later today, guys 😉

**Comment by custa1200** [comment]
Plus one on seeing this going again. As the others I am also seeing nothing when using the plugin

**Comment by Adrxx** [comment]
We have released a fix! Go try it out.

**Comment by MAJ3STIC** [comment]
Confirmed it's working now. Thank you again!
