### ISSUE TITLE
PMS

### ISSUE THREAD

**Issue by custa1200** [ment-mx/Prism#8]
Might be a bit tricky to do but it would be cool if it had PMS colours too to help print producers understand a digital palette.

**Comment by lalomts** [comment]
Hey, @custa1200, thanks for the idea!
I don't find a lot of cases where Sketch is used for printing, do you? Maybe it could be an interesting approach for the next release.

**Comment by Adrxx** [comment]
The thing is, you can only aproximate the hex to PMS color value, am I right?...

**Comment by okayjeffrey** [comment]
Pantone requires a Pantone printed swatch book and eye matching. Pantone is a standardized color system and computer screens are not :/

This would not work really well and would cause a lot of color inconsistency.

Get a Pantone book and match the colors by eye (in the daylight).

**Comment by custa1200** [comment]
On second thought it might be harder than thought. Might require a lookup/mapping from Pantone and no doubt licensing.

**Comment by Adrxx** [comment]
Yep, looks a little too complex and outside the goals of this plugin. But thanks for the idea, keep them coming!

If you don't mind, I'm gonna close this Issue ;)
